TICKERS = {
    'BTC':   ['BTC', 'bitcoin'],
    'ETH':   ['ETH', 'ethereum'],
    'BNB':   ['BNB', 'binance coin', 'binancecoin'],
    'USDT':  ['USDT', 'tether'],
    'SOL':   ['SOL', 'solana'],
    'ADA':   ['ADA', 'cardano'],
    'XRP':   ['XRP', 'ripple'],
    'DOT':   ['DOT', 'polkadot'],
    'LUNA':  ['LUNA', 'terra'],
    'DOGE':  ['DOGE', 'dogecoin'],
    'AVAX':  ['AVAX', 'avalanche'],
    'SHIB':  ['SHIB', 'shiba inu', 'shiba'],
    'CRO':   ['CRO', 'crypto.com'],
    'MATIC': ['MATIC', 'polygon'],
    'WBTC':  ['WBTC', 'wrapped bitcoin', 'wrapped btc'],
    'ALGO':  ['ALGO', 'algorand'],
    'LTC':   ['LTC', 'litecoin'],
    'UNI':   ['UNI', 'uniswap'],
}
